name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        python-version: 
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      run: python -m pip install -e .[dev]
    - name: Run tests
      run: pytest
