name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # run this once a week (wednesday) at 3 am UTC
    - cron: '0 3 * * 3'
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version: [
          '3.9',
          '3.10',
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      run: python -m pip install -e .[dev]
    - name: Generate coverage report
      run: |
        python -m pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  image_comparison_tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        dependencies: [dev]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup package
      run: python -m pip install ".[dev]"

    - name: Run image tests
      run: |
        python -m pytest --cov=./ --cov-report=xml -vvv --mpl --mpl-generate-summary=html --mpl-results-path=mpl_results tests/test_plotting.py

    - name: Upload pytest-mpl report
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: image_comparison_report
        path: mpl_results/*

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
